esphome:
  name: monitorswitcher8
  platform: ESP8266
  board: d1_mini

external_components:
  - source: my_components
    components: [
    ddc
  ]
    
# Enable logging
logger:
  level: DEBUG
  
i2c:
  scl: SCL
  sda: SDA
  scan: False
  frequency: 50khz

ddc:

sensor:
  - platform: ddc
    brightness:
      name: "Monitor Brightness"

# select:
#   - platform: hdmiddc
#     name: "HDMI Input Select"
#     id: hdmi_input_select
#     options: 
#       0x01: DISPLAYPORT
#       0x03: HDMI1
#       0x11: HDMI2
