esphome:
  name: drevil
  platform: ESP8266
  board: d1_mini

external_components:
  - source: my_components
    components: [
    a7105,
    ddc,
    neewer_light
  ]
    
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: drevil
    password: !secret ap_password
  
i2c:
  scl: SCL
  sda: SDA
  scan: False
  frequency: 50khz

spi:
  clk_pin: D5
  mosi_pin: D7
  miso_pin: D6
  interface: hardware

a7105:
  cs_pin: D8

ddc:

sensor:
  - platform: ddc
    brightness:
      name: "Monitor Brightness"

# select:
#   - platform: hdmiddc
#     name: "HDMI Input Select"
#     id: hdmi_input_select
#     options: 
#       0x01: DISPLAYPORT
#       0x03: HDMI1
#       0x11: HDMI2

binary_sensor:
  - platform: gpio
    pin: 
      number: D4
      inverted: true
    id: button_1
    name: Button 1
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: 
      number: D3
      inverted: true
    id: button_2
    name: Button 2
    filters:
      - delayed_on: 10ms

# sensor:
#   - platform: adc
#     id: photocell_measurement
#     pin: A0
#     name: "Photocell 0"
#     device_class: illuminance
#     update_interval: 500ms
#     unit_of_measurement: lx
#     filters:
#       - lambda: |-
#           return (x / 10000.0) * 2000000.0;
#     on_value_range: 
#       - above: 150
#         then:
#           - select.set: 
#               id: hdmi_input_select
#               option: "DISPLAYPORT"
#           - text_sensor.template.publish: 
#               id: usb_input_sensor
#               state: "1"              
#       - below: 150
#         then:
#           - select.set:
#               id: hdmi_input_select
#               option: "HDMI2"
#           - text_sensor.template.publish: 
#               id: usb_input_sensor
#               state: "2"

light:
  - platform: neewer_light
    id: left_panel
    name: Left Panel
    channel: 3
    group: 0x01
    cold_white_color_temperature: 5600 K
    warm_white_color_temperature: 3150 K
  - platform: neewer_light
    id: right_panel
    name: Right Panel
    channel: 3
    group: 0x41
    cold_white_color_temperature: 5600 K
    warm_white_color_temperature: 3150 K

text_sensor:
  - platform: template
    name: "Active USB Input"
    id: usb_input_sensor
